# Generated by Django 5.0.4 on 2024-11-27 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='evento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
            preserve_default=False,
        ),
    ]
